spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhangbiao
    url: jdbc:mysql://123.56.9.64:3306/sell?characterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 123.56.9.64
    port: 6379
    password: zhangbiao
server:
  context-path: /sell
wechat:
  # appId: wxf680b3a24675e2b8
  appId: wxf680b3a24675e2b8
  secret: 829fa90dd46ec05dd9d70dab8f8053f4
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: C:\Users\zhangbiao\Desktop\h5.p12
  templateMap:
    orderStatus: NSy7TtO5vw3CnenEyWAAGoVbMSGMQHNBgAuljBfU8wA
project:
  url:
    wechatMpAuthorize: http://zhangbiao.natapp1.cc
    wechatOpenAuthorize: http://zhangbiao.natapp1.cc
    sell: http://zhangbiao.natapp1.cc
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml